import GetData from "@/components/GetData";
import PostData from "@/components/PostData";
import GetData2 from "@/components/GetData2";
import PostData2 from "@/components/PostData2";

export const metadata = {
  title: "raja kumar",
  description: "Generated by create next app",
};

const Home = ()=>{
  return (
  <>
    <h1>Hello next js</h1>
    <PostData />
    <GetData />
    {/* <PostData2 /> */}
    {/* <GetData2 /> */}
  </>
  )
};

export default Home;